spring:
  application:
    name: arieslab-gateway
  cloud:
    gateway:
      routes:
        - id: ARIESLAB-USER-SERVICE
          uri: lb://ARIESLAB-USER-SERVICE
          predicates:
            - Path=/arieslab-user-service/**
          filters:
            - RewritePath=/arieslab-user-service/(?<segment>.*),/$\{segment}
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker
                fallbackUri: forward:/fallback/userServiceFallbackMethod
        - id: ARIESLAB-DEPARTMENT-SERVICE
          uri: lb://ARIESLAB-DEPARTMENT-SERVICE
          predicates:
            - Path=/arieslab-department-service/**
          filters:
            - RewritePath=/arieslab-department-service/(?<segment>.*),/$\{segment}
            - name: CircuitBreaker
              args:
                name: defaultCircuitBreaker
                fallbackUri: forward:/fallback/departmentServiceFallbackMethod
resilience4j:
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        registerHealthIndicator: true
  timelimiter:
    instances:
      defaultCircuitBreaker:
        timeoutDuration: 1200
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /_admin
      exposure:
        include: ["info", "health", "loggers", "metrics", "prometheus", "caches", "refresh"]
